
services:
  request-react:
    container_name: request-react
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src 
    stdin_open: true
    tty: true
