services:
  requestform:
    build:
      context: ./
      dockerfile: Dockerfile
    image: request-form
    container_name: requestform
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./:/var/www
      - requestform_data:/var/lib/mysql
    networks:
      - requestform
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3307
      DB_DATABASE: request_db
      DB_USERNAME: smct
      DB_PASSWORD: smct

  mysql:
    image: mysql:8.0
    container_name: request-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: request_db
      MYSQL_USER: smct
      MYSQL_PASSWORD: smct
      MYSQL_ROOT_PASSWORD: smct  
    volumes:
      - requestform_data:/var/lib/mysql
    networks:
      - requestform
    ports:
      - "3307:3306"

  request-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: request-phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80  # Expose phpMyAdmin on port 8080
    environment:
      PMA_HOST: mysql  # Use 'mysql' as the service name
      PMA_USER: smct
      PMA_PASSWORD: smct
    networks:
      - requestform

  nginx:
    image: nginx:alpine
    container_name: requestform-nginx
    restart: unless-stopped
    ports:
      - 8002:8002
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - requestform

volumes:
    requestform_data:  

networks:
  requestform:
    driver: bridge