
services:
  request-react1:
    container_name: request-react1
    restart: unless-stopped
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "8011:8001"
    volumes:
      - ../client:/app
      - /app/node_modules
      - ../client/src:/app/src 
    stdin_open: true
    tty: true
    networks:
      - react-network

  request-react2:
    container_name: request-react2
    restart: unless-stopped
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "8012:8001"
    volumes:
      - ../client:/app
      - /app/node_modules
      - ../client/src:/app/src 
    stdin_open: true
    tty: true
    networks:
      - react-network

  request-react3:
    container_name: request-react3
    restart: unless-stopped
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "8013:8001"
    volumes:
      - ../client:/app
      - /app/node_modules
      - ../client/src:/app/src 
    stdin_open: true
    tty: true
    networks:
      - react-network

  react-nginx:  
    image: nginx:alpine 
    container_name: request-nginx
    restart: unless-stopped    
    ports:                      
      - 8001:8001
    volumes:
      - ../client:/app
      - /app/node_modules
      - ..client//src:/app/src 
      - ../client/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - react-network
  
  requestform:
    build:
      context: ../server
      dockerfile: Dockerfile
    image: request-form
    container_name: requestform
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../server/storage:/var/www/storage
      - ../server/bootstrap/cache:/var/www/bootstrap/cache
      - ../server/:/var/www
      - requestform_data:/var/lib/mysql
    networks:
      - requestform
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3307
      DB_DATABASE: request_db
      DB_USERNAME: smct
      DB_PASSWORD: smct

  mysql:
    image: mysql:8.0
    container_name: requestform-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: backend
      MYSQL_USER: smct
      MYSQL_PASSWORD: smct
      MYSQL_ROOT_PASSWORD: smct  
    volumes:
      - requestform_data:/var/lib/mysql
    networks:
      - requestform
    ports:
      - "3307:3306"

  nginx:
    image: nginx:alpine
    container_name: requestform-nginx
    restart: unless-stopped
    ports:
      - 8002:8002
    volumes:
      - ../server/:/var/www
      - ../server/docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - requestform
  
volumes:
  requestform_data:  

networks:
  react-network:
    driver: bridge
  requestform:
    driver: bridge
